### ISSUE TITLE
Generate Score Components

### ISSUE THREAD

**Issue by Brallen** [banio-co/ColorGame#4]
- [x] Come up with equation for score (counting moves like in golf)
- [x] Display current score in its place in layout
- [ ] ~~Store high score for reuse~~ #17 
- [x] ~~If current score is higher than high score display the current score in the place of the high score~~
- [x] Display high score in its place in layout

**Comment by CubePresser** [comment]
![image](https://user-images.githubusercontent.com/26985451/162595724-9787a85d-f98b-4532-9bc8-173270ab2bdd.png)
